### ISSUE TITLE
How to increase text label size of annotation

### ISSUE THREAD

**Issue by apatewp** [neuml/txtmarker#4]
Very interesting lib, it is highly appreciated but it seems changing pdf-annotate default text annotate size from pdf.py has no effect on the label that is annotated on the output.pdf .

Any help is deeply appreciated

**Comment by davidmezzetti** [comment]
Are you referring to [line 232 on pdf.py](https://github.com/neuml/txtmarker/blob/master/src/python/txtmarker/pdf.py#L232)?

```python
# Add title annotation next to highlight
annotator.add_annotation("text", Location(x1=x1, y1=y1, x2=x2, y2=y2, page=page),
                         Appearance(fill=rgb + (1,), font_size=7, stroke_width=1, content=title))
```

If so, did you rebuild the library from source after making that change and reinstall?

**Comment by apatewp** [comment]
Thanks @davidmezzetti  , I am very newb and wasn't aware of the process of modifying packages.  Once again highly appreciate your work.

**Comment by davidmezzetti** [comment]
No problem, glad you were able to resolve the issue!
