### ISSUE TITLE
Is it possible to use single color on the word I input?

### ISSUE THREAD

**Issue by Clancyli** [neuml/txtmarker#6]
Hey dear devs,

I'd like to ask if that is possible to use one color on one word i give to the machine.
just like yellow for the word "first", blue for the "second".

have a nice day

**Comment by davidmezzetti** [comment]
This is not currently possible but would be a simple change. 

https://github.com/neuml/txtmarker/blob/master/src/python/txtmarker/pdf.py#L32

The logic can be changed to add an additional element to the highlights tuple with a color, defaulting to the index logic on line 39. We'll add this next time we have a release of txtmarker.

**Comment by Clancyli** [comment]
that'll be nice😀
