### ISSUE TITLE
multiple marks in one page?

### ISSUE THREAD

**Issue by EaglePPP** [neuml/txtmarker#7]
Hey @davidmezzetti ,

i'm back to bother you again lol.
Do you know how to mark one word's multiple results in a single page?
Somehow I have only managed to mark the first result of that word in every page, all of the other results remained unmarked.

best regards

**Comment by davidmezzetti** [comment]
Thank you for reporting this, it's possible this is a bug but I haven't been able to reproduce this error. I'll keep this open and take a closer look next time txtmarker has a new release.

**Comment by jasonarmbrecht** [comment]
I encounter this same issue. Very strange indeed.
