### ISSUE TITLE
Highlighter too slow to highlight sentences in pdf

### ISSUE THREAD

**Issue by muazhari** [neuml/txtmarker#9]
I want to do highlight some sentences in pdf, but the process is too slow. The average annotation process per sentence takes 0.04 seconds. The problem is in my use case that I have to annotate thousands of sentences. For example 1000 sentences instead becomes 1000*0.04 = 40 seconds, this is too slow. How to speed up the annotation process?

**Comment by davidmezzetti** [comment]
Have you considered [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) to achieve the desired performance? For example, if you have 4 cores with hyper-threading, you can create 8 processes to highlight.

Processing will scale close to linearly. In the example above, processing time is reduced down to 40/8 = 5 seconds. If you have 8 cores, its 2.5 seconds and so on.

**Comment by muazhari** [comment]
Okay, thanks for the idea. And, I think you must add it as a configurable feature in the next version. It is good to have.

**Comment by davidmezzetti** [comment]
Closing this issue. Multiprocessing is the best method to support this.
